version 1.0.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -36,31 +36,42 @@ else
     exit 1
 fi
 
-LSF_LIBS=""
-echo "Try to find libbat ..."
-if [ -f ${LSF_LIBDIR}/libbat.a ]; then
-    echo "Found in ${LSF_LIBDIR}"
-    LSF_LIBS="-L${LSF_LIBDIR} -lbat"
+if [ ! -z "$LSF_LIBS" ]; then
+	echo "Using LSF_LIBS environment variable: $LSF_LIBS"
 else
-    echo "Cannot find liblsf.a"
-    echo "Please check if LSF_ENVDIR is set properly."
-    exit 1
-fi    
+	echo "Try to find libbat ..."
+	if [ -f ${LSF_LIBDIR}/libbat.a ]; then
+		echo "Found in ${LSF_LIBDIR}"
+    	LSF_LIBS="${LSF_LIBDIR}/libbat.a"
+	else
+    	echo "Cannot find libbat.a"
+    	echo "Please check if LSF_ENVDIR is set properly."
+    	exit 1
+	fi    
 
-echo "Try to find liblsf ..."
-if [ -f ${LSF_LIBDIR}/liblsf.a ]; then
-    echo "Found in ${LSF_LIBDIR}"
-    LSF_LIBS="${LSF_LIBS} -llsf"
-else
-    echo "Cannot find liblsf.a"
-    echo "Please check if LSF_ENVDIR is set properly."
-    exit 1
-fi    
+	echo "Try to find liblsf ..."
+	if [ -f ${LSF_LIBDIR}/liblsf.a ]; then
+    	echo "Found in ${LSF_LIBDIR}"
+    	LSF_LIBS="${LSF_LIBS} ${LSF_LIBDIR}/liblsf.a"
+	else
+    	echo "Cannot find liblsf.a"
+    	echo "Please check if LSF_ENVDIR is set properly."
+    	exit 1
+	fi    
+fi
 
 echo "Check for libnsl ..."
 if [ -f /usr/lib/libnsl.so ]; then
 	echo "Found in /usr/lib"
 	LSF_LIBS="${LSF_LIBS} -lnsl"
+else
+	echo "Not found"
+fi
+
+echo "Check for libsocket ..."
+if [ -f /usr/lib/libsocket.so ]; then
+	echo "Found in /usr/lib"
+	LSF_LIBS="${LSF_LIBS} -lsocket"
 else
 	echo "Not found"
 fi
